version: '3.8'
networks:
  npm_default:
    external: true

services:
  # Base de données MongoDB
  mongodb:
    image: mongo:latest
    container_name: emergent-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword

  # API Backend (FastAPI)
  backend:
    build: ./backend
    container_name: emergent-backend
    environment:
      - MONGO_URL=mongodb://admin:secretpassword@mongodb:27017/emergent_db?authSource=admin
      - DB_NAME=irisdb
      - CORS_ORIGINS=https://iris.loasis.app
      - DISCORD_GUILD_ID=1081957992188088391
      - DISCORD_BOT_TOKEN=XXXXXX
      - DISCORD_CLIENT_ID=1530303803008749750
      - DISCORD_CLIENT_SECRET=HSs1jdRWg5fKYMDnIAL3nc0TAkSoqMNr
      - DISCORD_REDIRECT_URI=https://api.loasis.app/api/auth/discord/callback
      - APP_SESSION_SECRET=topsecret
      - DISCORD_HELPER_ROLE_ID=1499491909750755570
      - DISCORD_ADMIN_ROLE_ID=1503100661728936046
      - EMERGENT_LLM_KEY=000000
    depends_on:
      - mongodb

  # Application Frontend (React)
  frontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=https://api.loasis.app
    container_name: emergent-frontend
    depends_on:
      - backend

volumes:
  mongo-data:
